name: Dockfile_

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout name
        uses: actions/checkout@v3
    
      
      - 
         name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nishu1997/nodeapp
          
      -  
         name: Build and push
         uses: docker/build-push-action@v2
         with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
         name: SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@master
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
           
     
